POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhYnJpZWwxMjM0IiwiaWQiOiI2NzExNzRhOWQ4MGU4YTljZTE5ZTJjNTUiLCJpYXQiOjE3MjkxOTcyNDAsImV4cCI6MTcyOTIwMDg0MH0.ddxM35rFl480RI2HwkkL6QaHuKHfJjDTaP1Pmt3qFl8

{
    "title": "test3",
    "author": "test",
    "url": "http://haha.com/lmao"
}