PUT http://localhost:3003/api/blogs/66d241a7176af1a8ab0f9132
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhYnJpZWwiLCJpZCI6IjY2ZDI0MTkzMTc2YWYxYThhYjBmOTEyZSIsImlhdCI6MTcyNjQyMDU0MiwiZXhwIjoxNzI2NDI0MTQyfQ.8nsxBTRofR_0u_uxg9IU5b64s-eafcKyK4_rv4c3jSY

{
   "title":"new blog",
   "author":"question mark",
   "url":"random link",
   "likes": 60,
   "user": "66d24193176af1a8ab0f912e"
}

//existing id 66c101352fa18a68eb9fb78b
//non existing id 66c5f7178ac467eaff417e64